name: Supabase Heartbeat

on:
  schedule:
    # Runs once every 24 hours at 12:00 AM UTC (adjust as needed)
    - cron: "0 0 * * *"
  workflow_dispatch: # Enable manual triggering

jobs:
  api_call:
    runs-on: ubuntu-latest

    steps:
      - name: Supabase Heartbeat
        run: |
          curl -X GET "https://namethattune.vercel.app/api/callback?code=1234" \
            -H "Content-Type: application/json"
