name: Scheduled Login API Call

on:
  schedule:
    # Runs every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch: # Enable manual triggering

jobs:
  api_call:
    runs-on: ubuntu-latest

    steps:
      - name: Make API POST Request
        run: |
          curl -X POST "https://namethattune.vercel.app/api/login" \
            -H "Content-Type: application/json" \
